2018-12-07 00:04:19,017 ERROR: Exception on /index [GET] [in /home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaori/Desktop/flasky/app/routes.py", line 29, in index
    next_url=next_url,prev_url=prev_url)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kaori/Desktop/flasky/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/kaori/Desktop/flasky/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/kaori/Desktop/flasky/ven/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/kaori/Desktop/flasky/app/templates/base.html", line 48, in block "content"
    {% block app_content %} {% endblock %}
  File "/home/kaori/Desktop/flasky/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/kaori/Desktop/flasky/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.gravatar(70) }}" />
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avatar'
2018-12-07 00:04:28,212 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:56]
2018-12-07 00:14:15,877 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:57]
2018-12-07 12:04:00,750 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:57]
2018-12-08 21:26:38,926 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:57]
2018-12-08 21:29:32,658 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:57]
2018-12-08 21:32:08,619 INFO: Microblog startup [in /home/kaori/Desktop/flasky/app/__init__.py:57]
